import React, { useState, useEffect } from "react";
import { View, Text, ScrollView, Pressable, ActivityIndicator, Alert, Share } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useNavigation, useRoute } from "@react-navigation/native";
import type { RouteProp } from "@react-navigation/native";
import { Ionicons } from "@expo/vector-icons";
import Animated, {
  FadeIn,
  useAnimatedStyle,
  withRepeat,
  withSequence,
  withTiming,
  useSharedValue,
} from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import {
  analyzePersonBehavior,
  canUseAIAnalysis,
  MIN_LOGS_FOR_AI,
  type BehaviorAnalysis,
} from "../services/AIInsightsService";
import { getLogsByProfileId, getProfileById, type LogEntry } from "../database/db";
import { AIInsightCard } from "../components/AIInsightCard";
import type { RootStackParamList } from "../navigation/RootNavigator";

type AIInsightsRouteProp = RouteProp<RootStackParamList, "AIInsights">;

const COLORS = {
  green: "#00FF9C",
  red: "#FF0055",
  cyan: "#00F0FF",
  yellow: "#FFD600",
  purple: "#B026FF",
  dark: "#050508",
  surface: "#0D0D12",
  border: "#1A1A24",
};

export default function AIInsightsScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation();
  const route = useRoute<AIInsightsRouteProp>();
  const { profileId, profileName } = route.params;

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<BehaviorAnalysis | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [relationship, setRelationship] = useState<string>("");

  // Loading animation
  const pulseValue = useSharedValue(1);

  useEffect(() => {
    pulseValue.value = withRepeat(
      withSequence(withTiming(1.2, { duration: 800 }), withTiming(1, { duration: 800 })),
      -1,
      true
    );
  }, []);

  const pulseStyle = useAnimatedStyle(() => ({
    transform: [{ scale: pulseValue.value }],
  }));

  useEffect(() => {
    loadAndAnalyze();
  }, [profileId]);

  const loadAndAnalyze = async () => {
    try {
      setLoading(true);
      setError(null);

      // Load profile to get relationship type
      const profile = await getProfileById(profileId);
      if (profile) {
        setRelationship(profile.relationship);
      }

      // Load logs
      const profileLogs = await getLogsByProfileId(profileId);
      setLogs(profileLogs);

      // Check minimum logs requirement
      if (!canUseAIAnalysis(profileLogs.length)) {
        setError(
          `Need at least ${MIN_LOGS_FOR_AI} logs for AI analysis. You currently have ${profileLogs.length} log${profileLogs.length === 1 ? "" : "s"}. Add more behavioral data to unlock AI insights.`
        );
        setLoading(false);
        return;
      }

      // Perform AI analysis
      const aiAnalysis = await analyzePersonBehavior(
        profileLogs,
        profileName,
        profile?.relationship
      );
      setAnalysis(aiAnalysis);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (err: any) {
      console.error("Failed to load AI insights:", err);
      setError(err.message || "Failed to generate insights. Please try again.");
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!analysis) return;

    const shareText = `AI Behavioral Analysis - ${profileName}

RISK LEVEL: ${analysis.risks.level.toUpperCase()}
${analysis.risks.summary}

PATTERNS DETECTED:
${analysis.patterns.map((p, i) => `${i + 1}. ${p}`).join("\n")}

TIMELINE INSIGHTS:
${analysis.timeline_insights.map((t, i) => `${i + 1}. ${t}`).join("\n")}

RECOMMENDATIONS:
${analysis.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

Trend: ${analysis.health_trend.toUpperCase()}

---
Generated by VibeFlagger AI (Powered by Claude)`;

    try {
      await Share.share({
        message: shareText,
        title: `AI Analysis - ${profileName}`,
      });
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    } catch (err) {
      console.error("Share error:", err);
    }
  };

  const getRiskColor = () => {
    if (!analysis) return COLORS.cyan;
    switch (analysis.risks.level) {
      case "low":
        return COLORS.green;
      case "moderate":
        return COLORS.yellow;
      case "high":
        return COLORS.red;
      case "critical":
        return COLORS.red;
    }
  };

  const getTrendIcon = () => {
    if (!analysis) return "remove-outline";
    switch (analysis.health_trend) {
      case "improving":
        return "trending-up-outline";
      case "stable":
        return "remove-outline";
      case "declining":
        return "trending-down-outline";
    }
  };

  const getTrendColor = () => {
    if (!analysis) return COLORS.cyan;
    switch (analysis.health_trend) {
      case "improving":
        return COLORS.green;
      case "stable":
        return COLORS.cyan;
      case "declining":
        return COLORS.red;
    }
  };

  return (
    <View className="flex-1" style={{ backgroundColor: COLORS.dark }}>
      {/* Header */}
      <View
        style={{
          paddingTop: insets.top + 16,
          paddingBottom: 16,
          paddingHorizontal: 20,
          backgroundColor: COLORS.surface,
          borderBottomWidth: 1,
          borderBottomColor: COLORS.border,
        }}
      >
        <View className="flex-row items-center justify-between">
          <Pressable
            onPress={() => navigation.goBack()}
            className="mr-4"
            onPressIn={() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)}
          >
            <Ionicons name="arrow-back" size={24} style={{ color: COLORS.purple }} />
          </Pressable>
          <View className="flex-1">
            <Text className="text-xs font-mono" style={{ color: "#666", letterSpacing: 2 }}>
              AI ANALYSIS
            </Text>
            <Text className="text-lg font-mono font-bold" style={{ color: COLORS.purple }}>
              {profileName}
            </Text>
          </View>
          <View className="flex-row gap-2">
            {analysis && (
              <Pressable
                onPress={handleShare}
                className="p-2"
                onPressIn={() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)}
              >
                <Ionicons name="share-outline" size={22} style={{ color: COLORS.cyan }} />
              </Pressable>
            )}
            <Pressable
              onPress={loadAndAnalyze}
              className="p-2"
              disabled={loading}
              onPressIn={() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)}
            >
              <Ionicons
                name="refresh-outline"
                size={22}
                style={{ color: loading ? "#444" : COLORS.cyan }}
              />
            </Pressable>
          </View>
        </View>
      </View>

      {/* Content */}
      <ScrollView
        className="flex-1"
        contentContainerStyle={{ paddingBottom: insets.bottom + 20 }}
      >
        {loading && (
          <View className="flex-1 items-center justify-center py-20">
            <Animated.View style={pulseStyle}>
              <Ionicons name="sparkles" size={64} style={{ color: COLORS.purple }} />
            </Animated.View>
            <Text
              className="text-sm font-mono mt-6"
              style={{ color: "#888", letterSpacing: 1 }}
            >
              ANALYZING BEHAVIORAL PATTERNS...
            </Text>
            <ActivityIndicator size="large" color={COLORS.purple} style={{ marginTop: 20 }} />
          </View>
        )}

        {error && !loading && (
          <Animated.View entering={FadeIn} className="mx-5 mt-6">
            <View
              className="p-4 rounded-lg"
              style={{
                backgroundColor: `${COLORS.red}20`,
                borderWidth: 1,
                borderColor: COLORS.red,
              }}
            >
              <View className="flex-row items-start gap-2">
                <Ionicons name="alert-circle" size={20} color={COLORS.red} />
                <Text className="font-mono text-sm flex-1 leading-5" style={{ color: COLORS.red }}>
                  {error}
                </Text>
              </View>
              {logs.length < MIN_LOGS_FOR_AI && (
                <Pressable
                  onPress={() => navigation.goBack()}
                  className="mt-3 p-2 rounded items-center"
                  style={{ backgroundColor: `${COLORS.red}30` }}
                >
                  <Text className="font-mono text-sm" style={{ color: COLORS.red }}>
                    Go Back
                  </Text>
                </Pressable>
              )}
            </View>
          </Animated.View>
        )}

        {analysis && !loading && !error && (
          <View className="px-5 pt-5">
            {/* Risk Assessment Card */}
            <AIInsightCard
              title="Risk Assessment"
              content={[analysis.risks.summary, ...analysis.risks.concerns]}
              borderColor={getRiskColor()}
              icon="alert-circle"
              delay={100}
            />

            {/* Health Trend Indicator */}
            <Animated.View entering={FadeIn.delay(200)} className="mb-4">
              <View
                className="p-4 rounded-lg flex-row items-center justify-between"
                style={{
                  backgroundColor: COLORS.surface,
                  borderWidth: 1,
                  borderColor: COLORS.border,
                }}
              >
                <View className="flex-row items-center gap-3">
                  <Ionicons name={getTrendIcon()} size={32} color={getTrendColor()} />
                  <View>
                    <Text className="text-xs font-mono" style={{ color: "#666" }}>
                      RELATIONSHIP TREND
                    </Text>
                    <Text
                      className="text-lg font-mono font-bold uppercase"
                      style={{ color: getTrendColor() }}
                    >
                      {analysis.health_trend}
                    </Text>
                  </View>
                </View>
                <View
                  className="px-3 py-1 rounded"
                  style={{
                    backgroundColor: `${getRiskColor()}20`,
                    borderWidth: 1,
                    borderColor: getRiskColor(),
                  }}
                >
                  <Text
                    className="font-mono text-xs font-bold uppercase"
                    style={{ color: getRiskColor() }}
                  >
                    {analysis.risks.level}
                  </Text>
                </View>
              </View>
            </Animated.View>

            {/* Pattern Analysis Card */}
            <AIInsightCard
              title="Pattern Analysis"
              content={analysis.patterns}
              borderColor={COLORS.green}
              icon="analytics"
              delay={300}
              collapsible
            />

            {/* Timeline Insights Card */}
            <AIInsightCard
              title="Timeline Insights"
              content={analysis.timeline_insights}
              borderColor={COLORS.cyan}
              icon="time-outline"
              delay={400}
            />

            {/* Recommendations Card */}
            <AIInsightCard
              title="Recommendations"
              content={analysis.recommendations}
              borderColor={COLORS.purple}
              icon="bulb-outline"
              delay={500}
              collapsible
            />

            {/* Ask AI Button */}
            <Pressable
              onPress={() => {
                Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
                navigation.navigate("AIChat", { profileId, profileName });
              }}
              className="rounded-lg p-4 flex-row items-center justify-center gap-2 mt-2"
              style={{
                backgroundColor: `${COLORS.green}20`,
                borderWidth: 2,
                borderColor: COLORS.green,
              }}
            >
              <Ionicons name="chatbubbles" size={20} color={COLORS.green} />
              <Text className="font-mono font-bold" style={{ color: COLORS.green }}>
                Ask AI Questions
              </Text>
            </Pressable>

            {/* Metadata */}
            <View
              className="mt-4 p-3 rounded-lg"
              style={{
                backgroundColor: COLORS.surface,
                borderWidth: 1,
                borderColor: COLORS.border,
              }}
            >
              <Text className="text-xs font-mono mb-1" style={{ color: "#666" }}>
                Analysis Metadata
              </Text>
              <Text className="font-mono text-xs" style={{ color: "#888" }}>
                Data Points: {logs.length} | Model: Claude 3.5 Sonnet
              </Text>
            </View>
          </View>
        )}
      </ScrollView>
    </View>
  );
}
